In [1]:
import numpy

In [2]:
A = numpy.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
print(numpy.split(A, 2, axis=1))  # 对矩阵进行分割，行分成两份

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [6]:
print(numpy.array_split(A, 3, axis=1))  # 不均等的分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [8]:
print(numpy.vsplit(A, 3))  # 纵向分割，将行拿出来

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [9]:
print(numpy.hsplit(A, 2))  # 横向分割，将列拿出来

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
