In [2]:
import numpy

In [3]:
a = numpy.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [4]:
b = a
c = a
d = b

In [5]:
a[0] = 11
print(a)

[11  1  2  3]


In [6]:
b is a  # b 与 a 是相同的引用

True

In [7]:
print(b)  # a被改变后，b也会被改变

[11  1  2  3]


In [8]:
d is a

True

In [9]:
b1 = a.copy()  # 深层复制，b与a不再关联

In [10]:
b1 is a

False