In [1]:
import numpy

In [2]:
a = numpy.array([10, 20, 30, 40])
b = numpy.arange(4)

# 减法，加法类似
print(a, b)
print(a - b)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]


In [3]:
# 乘法，** 表示几次方的符号
print(b ** 2)  # 求平方
print(b ** 3)  # 求立方

[0 1 4 9]
[ 0  1  8 27]


In [5]:
# 查看b中哪些值小于3
print(b < 3)
# 查看b中哪些值等于3
print(b == 3)

[ True  True  True False]
[False False False  True]


In [9]:
# 矩阵运算
a1 = numpy.array([[1, 1], [0, 1]])
b1 = numpy.arange(4).reshape((2, 2))
print("a1 = ", a1)
print("b1 = ", b1)
print(a1 * b1)  # 元素逐个相乘
print(numpy.dot(a1, b1))  # 矩阵乘法
print(a1.dot(b1))  # 与上一行等价

a1 =  [[1 1]
 [0 1]]
b1 =  [[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [11]:
# 随机生成矩阵
a2 = numpy.random.random((2, 4))  # 随机生成0-1之间的矩阵
print(a2)

[[0.87639853 0.68789107 0.78061515 0.95668424]
 [0.0889301  0.47759904 0.9505018  0.12013533]]


In [12]:
print(numpy.sum(a2))  # 对矩阵所有元素求和
print(numpy.min(a2))  # 求所有元素的最小值
print(numpy.max(a2))  # 求所有元素的最大值

4.938755250983192
0.08893009774563654
0.9566842417671295


In [15]:
print(numpy.sum(a2, axis=1))  # axis=1代表对各行求和，=0表示对各列求和

[3.30158899 1.63716627]
