In [1]:
import numpy

In [3]:
A = numpy.array([1, 1, 1])  # A.shape=(3,) 表示A只是一个序列，有3各元素
B = numpy.array([2, 2, 2])
print(numpy.vstack((A, B)))  # 矩阵上下合并
print(numpy.hstack((A, B)))  # 左右合并

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [5]:
print(A[numpy.newaxis, :])  # 在行维度上增加一个维度
print(A[:, numpy.newaxis])  # 在列上增加一个维度

[[1 1 1]]
[[1]
 [1]
 [1]]


In [7]:
A1 = numpy.array([1, 1, 1])[:, numpy.newaxis]
B1 = numpy.array([2, 2, 2])[:, numpy.newaxis]
C = numpy.concatenate((A1, B1, B1, A1), axis=0)  # 在列上进行合并
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
