In [13]:
import numpy

In [14]:
A = numpy.arange(3, 15)
print(A)
print(A[3])  # 通过索引寻找元素

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [15]:
A1 = A.reshape((3, 4))
print(A1)
print(A1[2])
print(A1[2][1])  # 获取第2行第1列的数
print(A1[2, 1])  # 与上一行等价

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
12
12


In [16]:
print(A1[2:])  # 获取第二行

[[11 12 13 14]]


In [17]:
print(A1[1,1:3])  # 获取第1列的1到3行数

[8 9]


In [18]:
for row in A1:  # 迭代默认是行
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [19]:
for column in A1.T:  # 转置后迭代列
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [21]:
print(A.flatten())  # 将矩阵转为一个普通的列表
for item in A.flat:  # 与flatten()不同，flat返回一个迭代器
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
