In [1]:
import numpy

In [2]:
array = numpy.array([[1, 2, 3], [2, 3, 4]])

In [4]:
print(array)
print("number of dim:", array.ndim)
print("shape = ", array.shape)
print("size = ", array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape =  (2, 3)
size =  6


In [9]:
a = numpy.array([[2, 23, 4]], dtype=numpy.int)  # 指定数据类型
print(a.dtype)
print(a.shape)
print(a)

int32
(1, 3)
[[ 2 23  4]]


In [10]:
b = numpy.zeros((3, 4))  # 生成全0矩阵
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
b1 = numpy.ones((3, 4), dtype=int)  # 生成全1矩阵
print(b1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
a1 = numpy.empty((3, 4))  # 生成空矩阵
print(a1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a2 = numpy.arange(12).reshape((3, 4))  # arange生成一个序列，用法类似range()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a3 = numpy.linspace(1, 10, 20)  # 生成线段，在1到10之间生成20个点
print(a3)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
# numpy基础运算
