In [1]:
import numpy

In [2]:
A = numpy.arange(2, 14).reshape((3, 4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [4]:
print(numpy.argmin(A))  # 获取最小值的索引
print(numpy.argmax(A))

0
11


In [10]:
print(numpy.mean(A))  # 计算A的所有元素的平均值
print(A.mean())
print(numpy.average(A))  # 同样计算所有元素的平均值
print(numpy.median(A))  # 计算中位数
print(numpy.cumsum(A))  # 计算A的累加
print(numpy.diff(A))  # 计算A每两个数之间的差

7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
print(numpy.nonzero(A))  # 查找不等于0的元素，两个矩阵对应元素拼起来作为索引

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [15]:
A1 = numpy.arange(14, 2, -1).reshape(3, 4)
print(A1)
print(numpy.sort(A1))  # 对A1进行排序，逐行

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [16]:
print(A.T)  # 矩阵转置
print(numpy.transpose(A))  # 同样是转置

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [18]:
print(numpy.clip(A, 5, 9))  # A中所有<5的数等于5，>9的数等于9

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
